sudo: false
language: erlang
before_install: set -e
after_script: set +e
install: curl -#fSLo ~/epm https://s3.amazonaws.com/epm/epm && chmod +x ~/epm
after_install: ~/epm version
script:
  - if [[ "$TRAVIS_OTP_RELEASE" = '20.2' ]] && [[ "$TRAVIS_EVENT_TYPE" = 'cron' ]]; then make update; fi
  - ~/epm eunit
  - '[[ 0 -eq $(git --no-pager diff | wc -l) ]]'
notifications:
  email:
    on_success: never
otp_release:
  - 22.0
  - 21.0
  - 20.3
  - 19.3
